### ISSUE TITLE
unstable hashrate CK5

### ISSUE THREAD

**Issue by abdulllh** [goldshellminer/firmware#1]
after latest update, hashrate is fluctuating between 10.2 - 13 TH/s

**Comment by abdulllh** [comment]
![Screenshot_20210612-142924_SparkHub](https://user-images.githubusercontent.com/34600903/121774318-ae972b00-cb8a-11eb-99a4-996fabdd68b1.jpg)


hashrate before and after the update of CK5

**Comment by Canonip** [comment]
It would be nice to have a repository with all firmware versions, so we can downgrade to the previous firmware in case there are any issues.

**Comment by abdulllh** [comment]
> It would be nice to have a repository with all firmware versions, so we can downgrade to the previous firmware in case there are any issues.

I regret updating my miners 
I hope someone could make a custom firmware with higher hashrate

**Comment by goldshellminer** [comment]
> after latest update, hashrate is fluctuating between 10.2 - 13 TH/s


> after latest update, hashrate is fluctuating between 10.2 - 13 TH/s

  the updates will not  affect hashrate in theory. How about the  hashrate in recent days?
