### ISSUE TITLE
Goldshell KA box pro issue with TH 

### ISSUE THREAD

**Issue by vforv** [goldshellminer/firmware#101]
Instead of getting 1.6 TH, I am getting 1.2 on Ka box pro

![IMG_20240609_124700_463](https://github.com/goldshellminer/firmware/assets/10942178/f74b64ed-8156-4cd6-9043-0916feb0e0d7)

What can be reason I updated firmware last avaliable Ka box

**Comment by vforv** [comment]
I figured out that need some specific firmware for it can anyone send it?

**Comment by jurado1993** [comment]
Donde podemos conseguir ese firmware

**Comment by Spindler360** [comment]
This is also the case with my kaboxpro. 1.2 to 1.4 th after 2 days. strange

**Comment by Spindler360** [comment]
btw @vforv I can see in your pic you have not the pro. the model discription shows "Goldshell-KABox" not "Goldshell-KABoxPro".
 
Have you perhaps installed the wrong update firmware? 

I see you use Firmware Version 2.2.7. This is only for the "normal" KABox. Not for the KaBoxPro.

**Comment by Pascalduc** [comment]
My KA Box Pro was working fine for a month then dropped to 1.3 TH/s.
I sent my log to Goldshell, but they want me to spend half the cost of the miner on courier shipping to send it back to Hong Kong.
With what I'm losing, the math doesn't make sense so I give them a bad review for poor after sale service.
