### ISSUE TITLE
[Request] please add miner log viewer

### ISSUE THREAD

**Issue by avenpace** [goldshellminer/firmware#14]
It would be really useful for the user if there is miner log access to help use debug connection problem
As I recently having problem connecting to Luxor pool with correct credential while it work perfectly in the past
Checked with pool support and all things is fine, but cannot see what really happen with my miner unit as there are no log viewer

**Comment by Xandrianx** [comment]
http://min.er.i.p/#/debug

**Comment by atlonxp** [comment]
Wow, it's already there but never been documented!

Thanks dude
