### ISSUE TITLE
[request] Add changes log for every firmwares update

### ISSUE THREAD

**Issue by atlonxp** [goldshellminer/firmware#15]
It would be the best if you add changes log everything you add new firmwares.

This is important to the users to be aware, just in case somethings go wrong after the update.

**Comment by maxfunky** [comment]
yes you need to add this! I was looking for the changes log but can't find it..

**Comment by goldshellminer** [comment]
Thanks for your suggestion, will forward it to the R&D team.
Besides, we had a similar function on the main page, click "README" and then you will know what feature we upgrade on the new firmware. 

<img width="460" alt="寻找更新固件的功能" src="https://user-images.githubusercontent.com/66982429/190372235-353001a7-f2b6-4943-acda-185ee0ef9e9d.png">
