### ISSUE TITLE
Leds of MineDOGE is always on when I update firmware to 2.1.1

### ISSUE THREAD

**Issue by WowWatchdoge** [goldshellminer/firmware#17]
Old version firmware only blue led was flashing, MineDOGE works fine except the leds, thanks! 

![image](https://user-images.githubusercontent.com/87231192/131850529-e50167a4-2b5f-403d-be53-65ffa55d1ba6.png)

![image](https://user-images.githubusercontent.com/87231192/131850881-76cd44e7-d947-4855-99cb-b29961041b57.png)

**Comment by MelasDigital** [comment]
I have the same problem with CK5. After the update, both LEDs are lit, the IP gets, but the web interface is unavailable.

**Comment by goldshellminer** [comment]
> I have the same problem with CK5. After the update, both LEDs are lit, the IP gets, but the web interface is unavailable.

Have you tried factory reset yet? If not working, pls flash your card to the 2.2.3 firmware version.
