### ISSUE TITLE
powerplan or fan control missing

### ISSUE THREAD

**Issue by tojefest** [goldshellminer/firmware#19]
``Hi, goldshell kd5 i can`t change anything. I have very cold place for this miner and fan works with 5100rpm. Is very big noise (noizy). Can i log into ssh or something to change that? I have temp 58C and cant change fan speed? oh come on..... With web Gui i saw only powerplan but is only one: hasratemode. Can anybody could help me? If there isn`t any control for poweruser is a huge issue.``

**Comment by jaspi72** [comment]
same on ck5.. 
I want to lower fan speed under 5100 if running temp is like now 70degrees.
And starting is wery problematic. 
If temp is low miner doesnt want to start so fan speed is way too hight on start.

**Comment by jaspi72** [comment]
![kuva](https://user-images.githubusercontent.com/34282195/133727164-889d4e9f-e905-424d-824d-6cd38ae7f2b8.png)

**Comment by crypto-citizen** [comment]
Fan speeds were fine on CK5 with firmware 2.0.3, now with firmware 2.1.1 fans are constantly running @ 5100rpm. Same issue is with HS5. 
Goldshell, please enable us an option to change fan power mode based on ambient temperature🌡 or suggest alternative solution so that we can select fan speed via web interface. Thank you

**Comment by crypto-citizen** [comment]
![Screenshot_20210918-144530_Brave](https://user-images.githubusercontent.com/90971266/133891018-c3dd3549-634e-4fbc-b540-7f7754db9a13.jpg)

CK5

**Comment by crypto-citizen** [comment]
Dear support, it's been two weeks since my last post. Can we get a reply on the above topic?

**Comment by glob002** [comment]
Same to me, can you please add more options to tweak fan speed, I want to run it at 5600-5800 constantly, or at least add dropbox to pick % for fans

**Comment by goldshellminer** [comment]
> `` Hi, goldshell kd5 i can`t change anything. I have very cold place for this miner and fan works with 5100rpm. Is very big noise (noizy). Can i log into ssh or something to change that? I have temp 58C and cant change fan speed? oh come on..... With web Gui i saw only powerplan but is only one: hasratemode. Can anybody could help me? If there isn`t any control for poweruser is a huge issue. ``

Hello, we have fixed this, pls upgrade your firmware to 2.2.3version.

**Comment by goldshellminer** [comment]
> Dear support, it's been two weeks since my last post. Can we get a reply on the above topic?

Hello, we have fixed this, pls upgrade your CK5 firmware to 2.2.3version.

**Comment by imannourih** [comment]
Hello, I have an lt5 pro miner.  I want to know how I can put my miner in low power mode, is it possible?
