### ISSUE TITLE
HS5 network connectivity

### ISSUE THREAD

**Issue by Genenex** [goldshellminer/firmware#2]
I just received my HS5 with the 2.0.3 firmware and .A3 hardware version.

The miner will boot up, give fast flashing green led (during startup procedure where fan goes from slow to fast and back to slow), then the miner gives a slow blinking red LED indicating some kind of network issue.

Tried various pools, reboots, resets, etc.  Network works, ethernet cable tested and working.  

Help??

**Comment by goldshellminer** [comment]
> I just received my HS5 with the 2.0.3 firmware and .A3 hardware version.
> 
> The miner will boot up, give fast flashing green led (during startup procedure where fan goes from slow to fast and back to slow), then the miner gives a slow blinking red LED indicating some kind of network issue.
> 
> Tried various pools, reboots, resets, etc. Network works, ethernet cable tested and working.
> 
> Help??

Dear Customer:
           The miner  will ping  fixed server to check  network  is connected successful ot not .  please check if your firewall have disabled the ICMP

**Comment by Genenex** [comment]
> > I just received my HS5 with the 2.0.3 firmware and .A3 hardware version.
> > The miner will boot up, give fast flashing green led (during startup procedure where fan goes from slow to fast and back to slow), then the miner gives a slow blinking red LED indicating some kind of network issue.
> > Tried various pools, reboots, resets, etc. Network works, ethernet cable tested and working.
> > Help??
> 
> Dear Customer:
> The miner will ping fixed server to check network is connected successful ot not . please check if your firewall have disabled the ICMP

Hi,

I have tried both with ICMP disabled and enabled, neither seems to fix the issue.  After changing to enabled from disabled I applied the settings, did a reboot of the router, then unplugged and waited 30 seconds and plugged back in.

Any other possible things I could try?

**Comment by Genenex** [comment]
Got the HS5 to connect, tried 4 different routers.  One ASUS, two netgears, and one belkin.  The oldest netgear worked.

However, now the miner will run for about 16-20 hours then start disconnecting and restarting about 1-5 times an hour, causing extremely low hashrate and a lot of fan noise each time it restarts.
![Capture](https://user-images.githubusercontent.com/85901395/123032830-8504ad80-d39b-11eb-97c5-9d1679324fd0.JPG)
