### ISSUE TITLE
DNS Resolution with Manual IP and DNS Assigned. Mine Doge Firmware 2.1.2

### ISSUE THREAD

**Issue by Hackpig1974** [goldshellminer/firmware#23]
I am seeing an issue with this firmware. (2.1.2 for Mini Doge) If you restart the device, when it boots back up it will not re-connect to the pool. It sits there not connected. You can make it connect by going to the system tab, and the clicking "Apply" under the DNS section. Then when you flip back to the miner tab you will see the pool connection indicator change from grey to green showing that is connected to the pool. Then the device will begin hashing again.

This may only be an issue when you have statically assigned an IP address and DNS. I can reproduce it every time by just rebooting the device. This should be investigated. Thanks. I have seen no other issues with this firmware.

**Comment by cryptominerht** [comment]
I have the same problem - if i manually set IP address it said the mini doge is not connected to WAN but if i change it back to DHCP, it works again.

**Comment by Hackpig1974** [comment]
@cryptominerht They really should investigate why static IP and DNS can't resolve properly on a reboot. It is so easy to reproduce and would me an easy fix at fixing an issue. So far, no response.

**Comment by cryptominerht** [comment]
it is okay, I don't really see a different between 2.1.1 and 2.1.2, I have two  mini doges running on 2.1.1 and they are working just fine (and somehow on a slightly higher hash rate too). I may downgrade the new one to 2.1.1

**Comment by Hackpig1974** [comment]
@cryptominerht I have 6 of them and on average have little to no issue with my mini doge. But if power flickers or there is an issue they don't resolve the pool. Maybe with enough time they will, not sure. If I get time I might just try and reboot one and start a timer to see how long it takes before it starts hashing again. I just hate playing with my money. HAHA

**Comment by thomann061** [comment]
@goldshellminer Please fix this issue. When the miner is assigned a static ip address, and the power goes out or the machine reboots. We have to manually click apply on the DNS Settings page, to start the miner again.

**Comment by goldshellminer** [comment]
> @cryptominerht I have 6 of them and on average have little to no issue with my mini doge. But if power flickers or there is an issue they don't resolve the pool. Maybe with enough time they will, not sure. If I get time I might just try and reboot one and start a timer to see how long it takes before it starts hashing again. I just hate playing with my money. HAHA

Hello, have you met the same issue when upgrading to the recent firmware (2.1.3/2.1.4/2.2.3)?

**Comment by goldshellminer** [comment]
> @goldshellminer Please fix this issue. When the miner is assigned a static ip address, and the power goes out or the machine reboots. We have to manually click apply on the DNS Settings page, to start the miner again.

Hello, have you met the same issue when upgrading to the recent firmware (2.1.3/2.1.4/2.2.3)?

**Comment by thomann061** [comment]
Now, the static dns does not work....

**Comment by goldshellminer** [comment]
> 

Pls contact the support team to get more support, Link: https://www.goldshell.com/support-center/
