### ISSUE TITLE
Miner not working

### ISSUE THREAD

**Issue by Bliss118** [goldshellminer/firmware#24]
Hi I purchased two KDA boxes. At the start I could not get either of them working then one just started to work since then it has stopped and is showing as dead in DXpool and no light are on.

With miner 2, after lots of back and forth with support, they asked me to burn a .img to an SD to restart the miner when I insert the card the light blinks as if it recognises the SD card but no burn happens. 

Any help would be appreciated.

**Comment by goldshellminer** [comment]
Hi, have you solved this problem yet? If still not working, pls follow up on your previous ticket and get support from the team. Thanks
