### ISSUE TITLE
Increase mining hash rate on goldshell LB box

### ISSUE THREAD

**Issue by Parrapushen** [goldshellminer/firmware#25]
Is there a way to change the mining algorithm to find a more profitable one? since the miners (LB, KD, HS, CK, Mini Doge) are practically the same inside ... I HAve a LB-BOX  and Doge

**Comment by pllumiikr** [comment]
i tried  all it wont work  you need an expert to send you the right update in order to mine other crypto with the same box   i been trying to figure it out for a while now  but not lucky as of now   and my ckb   is over working with speed and then just stops mining
