### ISSUE TITLE
Goldshell HS5 hashrate issue

### ISSUE THREAD

**Issue by ramsha30** [goldshellminer/firmware#27]
my goldhsell hs 5 is minning about 125 HNS A day only .the pool used is Viabtc 
though everywhere it says approximetly 260 HNS per day will be mined.;However thats not the case
please help

**Comment by goldshellminer** [comment]
Hi, have you solved this problem yet? If not, pls check average hashrate reaches 2700GH/S or not.

**Comment by ramsha30** [comment]
i want to order PSU For hs5
