### ISSUE TITLE
CK5 CPB0 not working after firmware update CK5-2.1.4 (and after 4 hours, hashrate dropped down to 2TH/s)

### ISSUE THREAD

**Issue by lerasah** [goldshellminer/firmware#32]
- Homepage ![Imgur Image](http://i.imgur.com/aRlRzk6.png)
- Chips ![Imgur Image](https://imgur.com/RfiKG6K.png)
- [miner-Mon Oct 25 2021 22_42_09 GMT+0530 (India Standard Time)](https://pastebin.com/raw/RSemHyrh)
- [monitor-Mon Oct 25 2021 22_42_49 GMT+0530 (India Standard Time)](https://pastebin.com/raw/wtw8gnvX)
- [syslog-Mon Oct 25 2021 22_41_58 GMT+0530 (India Standard Time)](https://pastebin.com/raw/JD1ZnkLg)

**Comment by THECOMPANY2** [comment]
min isnt working at all cant even ge the ip addres any moro what did you doo

**Comment by lerasah** [comment]
> min isnt working at all cant even ge the ip addres any moro what did you doo

that's a frequent error that happens every ~48 hours.. make sure you reboot once a day.. (I do this using an automated tool)
