### ISSUE TITLE
CKBOX unable to disable WiFi

### ISSUE THREAD

**Issue by gwaitsi** [goldshellminer/firmware#35]
I am unable to disable the WiFi on 

Firmware version2.1.1
Hardware version40.40.HA

The button is not selectable, or does not react to clicking on it.

**Comment by gwaitsi** [comment]
this seems to be an initiation bug. Workaround is to connect to a wifi network, and then you are able to disable

**Comment by plittlefield** [comment]
Did this work for you?

I have a KDBoxPro on firmware 2.2.6 and I cannot disable the WiFi ...

**Comment by gwaitsi** [comment]
> Did this work for you?
> 
> I have a KDBoxPro on firmware 2.2.6 and I cannot disable the WiFi ...

did you try my suggestion? connect to a wifi network, then disable it.

**Comment by plittlefield** [comment]
Just tried.  It connects to the wifi but **the toggle button is still inactive**.  This is my screen ...

![image](https://github.com/goldshellminer/firmware/assets/8265704/625c0e15-26b8-4dc0-b126-a31bda373b8e)

**Comment by plittlefield** [comment]
... so I pressed DISCONNECT and then tried the toggle slider but it is still inactive and does not work.
