### ISSUE TITLE
HS-Box: Wifi does not connect to any network

### ISSUE THREAD

**Issue by burgertyven** [goldshellminer/firmware#40]
Info:
-  HS-Box with wifi antenna
-  Purchased Nov 2021
-  firmware-Goldshell-HSBox-2.1.2.cpb

Issue:
-  Does Wifi hardware recognise available networks: YES
-  Does Wifi connect to any networks: NO 

Tested:
- 2.4Ghz + 5Ghz
- DHCP + Manual IP assignment
- Confirmed that other devices connect to networks with success
- Downgrade of firmware to: firmware-Goldshell-HSBox-2.0.6q.cpb (does not support wifi)

**Comment by burgertyven** [comment]
Solution: Goldshell Mini-Box miners dont support long Wifi passwords. Shorter passwords solved the issues.

**Comment by surfrider686** [comment]
I am not sure how this answers my question

Regards,
Ted Anderson
732-977-7743

**Comment by burgertyven** [comment]
> I am not sure how this answers my question Regards, Ted Anderson 732-977-7743
> […](#)
> Sent from my iPhone
> On Dec 9, 2021, at 7:57 PM, burgertyven ***@***.***> wrote: ﻿ Closed #40. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

What ?
