### ISSUE TITLE
Ck5 issue 

### ISSUE THREAD

**Issue by oj19991** [goldshellminer/firmware#41]
Hi 
I just bought CK5 miner 
Im having issues with it 
When i put my pool address it doesn’t mine and the hashing rate showing 000 
I noticed also that the hardware version shows some xxx 
Can anyone please help me with it 
I tried to upgrade to the new update but its not uploading to the miner 

any ideas how to fix

**Comment by goldshellminer** [comment]
Have you fixed this problem yet? If not working, pls upgrade to latest 2.2.3 version: https://github.com/goldshellminer/firmware/blob/master/firmware-Goldshell-CK5-2.2.3.cpb
