### ISSUE TITLE
Unable to boot LT5Pro on Latest firmware

### ISSUE THREAD

**Issue by scottharman** [goldshellminer/firmware#44]
Hi @goldshellminer  - has anyone had issues with the latest firmware?
Goldshell shipped a replacement PSU but it didn't work with the 2.1.0 firmware, so they suggested reflashing it with 2.1.1, but now it won't boot.  Just a flashing red light
Can someone supply a recovery image so I can try and reflash again?.

**Comment by goldshellminer** [comment]
Have you solved this problem yet? If not, pls upgrade firmware to the latest 2.2.3 version :https://github.com/goldshellminer/firmware/blob/master/firmware-Goldshell-LT5Pro-2.2.3.cpb

If still not working, pls attached the replacement PSU to get more help from after-sale team, Thanks
