### ISSUE TITLE
Mini Doge LTC miner keep stopping 

### ISSUE THREAD

**Issue by z7737546436** [goldshellminer/firmware#46]
I own 10 Mini Doge since July 2021 for the last couple of months my miner going offline by themself 1st I thought it might be a Network issue but I change all my cables and test my network modem. I discover there are no issues with my home network or from my service provider. Every time Miner stops mining some time all of them or sometimes only a couple of thems green LED turns red while network green and yellow lights are still present. They stay in this state for while then turn the red LED light back to green blow have aired out of the system and start mining 
There is no error found on F2Pool they are up and running my other computer in the house which also mining different coins show no sign of discontinuity they are all up and running 
I am using 80+ Gold standard PSU
miner current Firmware version is 2.0.2 and I mine 24/7 none stop 
Can someone please let me know why miners are acting in such way 
Thanks

**Comment by engcboy** [comment]
This was an older post, that seems to be an old problem with 2.02 firmware.  2.1.2 and 2.1.4 working
