### ISSUE TITLE
KD BOX FIRMWARE 2.0.7 100% reject rate

### ISSUE THREAD

**Issue by dubbb13** [goldshellminer/firmware#5]
i have 1 running 2.0.6 fine, and got one today with 2.0.5 and it wouldnt let me select the miner tab to add my pool etc. upgraded to 2.0.7 and cant get a thing accepted. 100% reject rate. 
I see this is not the only one. Please someone provide this 2.0.6 firmware please
@schua @goldshellminer

**Comment by goldshellminer** [comment]
Sorry for that. Please email to hello@goldshell.com or submit a ticket [submit](https://www.goldshell.com/ticket_new/)

**Comment by tianchaijz** [comment]
Now poolflare fixed this issue, due to some legacy codes, the new 2.0.7 firmware add chain to the `mining.submit` params, doesn't pass the json schema validation.
