### ISSUE TITLE
ck6 firmware

### ISSUE THREAD

**Issue by attilio1978** [goldshellminer/firmware#52]
hi by mistake i installed the latest ck5 firmware on a ck6 ... now i need the original ck6 firmware thanks

**Comment by Technocityusa** [comment]
Hello , I have ck6 and not hashing issue , did you able to find ck6 firmware ?

**Comment by attilio1978** [comment]
Yes I find firmware

Il giorno dom 20 feb 2022 alle 17:31 Technocityusa ***@***.***>
ha scritto:

**Comment by Technocityusa** [comment]
could you please share with me ? how can i download it ?

**Comment by attilio1978** [comment]
Give me your mail

Il giorno dom 20 feb 2022 alle 18:36 Technocityusa ***@***.***>
ha scritto:

**Comment by Technocityusa** [comment]
technocityusa gmail , thank you very much

**Comment by Technocityusa** [comment]
hey did you able to send it ?
