### ISSUE TITLE
update kd5 now not working

### ISSUE THREAD

**Issue by stickygreen0** [goldshellminer/firmware#56]
made the update 2.2.1...  miner restart and then no acces and red and green light cant access miner
do i need a special programm to install firmware on sd card or just dro file in it ?

i need help

**Comment by Dikrix75** [comment]
This is the same problem for me. Did you find a solution?

**Comment by Technocityusa** [comment]
Mine was power unit . But try doing update firmware . If not , either control board or psu .

**Comment by goldshellminer** [comment]
Hey, there are some solutions for you, pls follow the below steps:
1) Upgrade to the latest 2.2.3 version: https://github.com/goldshellminer/firmware/blob/master/firmware-Goldshell-KD5-2.2.3.cpb
2) If still not working, pls flash your SD card to check if solve or not. Contact support to get flash firmware: https://www.goldshell.com/support-center/
