### ISSUE TITLE
Request to release firmware source code

### ISSUE THREAD

**Issue by Phara0h** [goldshellminer/firmware#6]
Can you please release the firmware opensource?

**Comment by goldshellminer** [comment]
This firmware is not just an application. 
It's a whole platform and solution. The firmware will communicate with algo-chips directly.  

As we are still in a fiercely competitive environment (many algo-chip startup company established this year), we have no plan to publish right now.

**Comment by Phara0h** [comment]
> This firmware is not just an application.
> It's a whole platform and solution. The firmware will communicate with algo-chips directly.
> 
> As we are still in a fiercely competitive environment (many algo-chip startup company established this year), we have no plan to publish right now.

Makes sense, don't want competitors to copy and paste code. You could make it GPL 3  and then sue if they don't make a contract with you. Do you guys use your own asics or use chips that all your competitors have access too?

**Comment by luke-jr** [comment]
You are using my code, which is already GPL. You are REQUIRED to release it open source, or you are infringing!
