### ISSUE TITLE
ckbox stopped working after 24hrs, with no blue led

### ISSUE THREAD

**Issue by enrell69** [goldshellminer/firmware#60]
hi folks.

need your help on this

1) CKBox with no blue led and stopped mining but ok for PSU + LAN
2) turn off the miner and let it rest for hours
3) it works when i turned it on
4) after 24hrs, the same thing happened, stopped mining, no blue led
5) repeat 2)

Please help !!

Thank you

**Comment by goldshellminer** [comment]
Hey, could you solve this issue yet? If not, pls follow the below steps: 
1) If your miner with the old FW after checking, pls upgrade to the latest one 2.2.4 file: https://github.com/goldshellminer/firmware/blob/master/firmware-Goldshell-CKBox-2.2.4.cpb
2) If you fail to upgrade, pls contact support for more solutions via the website: https://www.goldshell.com/support-center/
