### ISSUE TITLE
Goldshell CK6

### ISSUE THREAD

**Issue by Technocityusa** [goldshellminer/firmware#61]
I have a new ck6 , its not hashing. I have tried factory reset. different ethernet connections. its shows at dxpool but no hash rate.
anyone can help ?

**Comment by Juano102** [comment]
im guessing goldshell is a scam

**Comment by goldshellminer** [comment]
Hi, Can you get all logs of CK6 miner?And send me these log,Let me check this miner,Thank you!

**Comment by goldshellminer** [comment]
> I have a new ck6 , its not hashing. I have tried factory reset. different ethernet connections. its shows at dxpool but no hash rate. anyone can help ?

Hey, have you contacted the support team, and got any solution to fix it?
