### ISSUE TITLE
Goldshell CK6 Firmware

### ISSUE THREAD

**Issue by Technocityusa** [goldshellminer/firmware#62]
Hello, anyone has CK6 firmware ? i have the machine running but not hashing ? anyone know the Issue ?

**Comment by Juano102** [comment]
I have the same

**Comment by BigCryptoRush** [comment]
I have the same problem. Anyone have a solution?

**Comment by goldshellminer** [comment]
Hi,Can you send me your all logs of CK6 miner?I can help you check your miner status.

**Comment by xKhaimera** [comment]
Just got my Goldshell-MiniDOGE this week and I am having this same reoccurring issue. The hash rate will be normal for 4-5 hours and then the hash rate will fall off but my machine will continue running. After resetting my machine everything will go back to normal for a few hours until it falls off again.
