### ISSUE TITLE
Mini Doge start up issue

### ISSUE THREAD

**Issue by mshmity** [goldshellminer/firmware#63]
My mini doge worked fine for several months then started getting CPBO Failed to startup. I have loaded new firmware version 2.2.1 and even tried version 2.1.4 but same thing. I have heard older version of firmware work but can't find older versions.

Please help.

**Comment by mshmity** [comment]
Ok now I have tried installing firmware version 2.1.1 from a micro SD card using the recommended steps. I can see that I have indeed installed firmware version 2.1.1 but still getting CPBO Failed to startup. 

Any Ideas????

**Comment by goldshellminer** [comment]
This is probably that your hashboard CPB0 has an issue on it, pls contact support via the website link: https://www.goldshell.com/support-center/
