### ISSUE TITLE
MiniDoge Firmware 2.2.1 FAULTY

### ISSUE THREAD

**Issue by JCBDigga** [goldshellminer/firmware#66]
Upgraded from 2.01 firmware due to having some issues with the miner loosing internet connection and seen recommendations to do so. However the firmware doesn't hash correctly maxed out at 22MH. Downgraded back to 2.01 and hit 160MH straight away again. 

In my experience, do not install this firmware.

**Comment by diaconom** [comment]
Reset to default settings - this resolved same issue I had with mine.

**Comment by goldshellminer** [comment]
> 
Pls upgrade your firmware to the latest one 2.2.3version. We improve the fan control system: https://github.com/goldshellminer/firmware/blob/master/firmware-Goldshell-MiniDOGE-2.2.3.cpb.
