### ISSUE TITLE
New KD-lite miner came new with virus on it

### ISSUE THREAD

**Issue by mshoub** [goldshellminer/firmware#69]
https://user-images.githubusercontent.com/107776421/174459385-501678e1-6092-4cb1-9da0-0f7e91836c9a.mp4

https://user-images.githubusercontent.com/107776421/174459386-7daffd3d-88be-4a26-ac44-26f3b1870049.mp4

attacker keeps changing the mining pool taking control of the miners hashing power! how do I fix this?

**Comment by goldshellminer** [comment]
Pls, burn the SD card first via attachment "burn-Goldshell-KDLITE_MCB_V4_3-2.2.7". Then upgrade to latest firmware-Goldshell-KDLITE-2.2.7.cpb. Link: https://github.com/goldshellminer/firmware/blob/master/firmware-Gold
[burn-Goldshell-KDLITE_MCB_V4_3-2.2.7.zip](https://github.com/goldshellminer/firmware/files/8991042/burn-Goldshell-KDLITE_MCB_V4_3-2.2.7.zip)
shell-KDLITE-2.2.7.cpb
