### ISSUE TITLE
KD-Box Pro: Please add an option in settings to use other fans

### ISSUE THREAD

**Issue by maka1000** [goldshellminer/firmware#70]
Hi

Please add a feature, that I can use other PWM Fans then the original. In the moment, when I use as example Noctua NF-A8 (PWM) fans, I get an error in my Goldshell Dashboard, that there are no fans or there is a problem with my fans (but of course they are working fine).

It would give more options to use KD-Box Pro in noise sensitive locations.

**Comment by goldshellminer** [comment]
Dear customer,
Unfortunately, this function cannot be implemented in a short time. In the setting file, each miner's maximum speed is listed. Different brands of fans can be replaced with the same speed as the original fan, but it is not feasible to adapt fans with different speeds.
