### ISSUE TITLE
Goldshell KD6 (4 Board 26Th) Firmware Update For 2.40.SA Hardware

### ISSUE THREAD

**Issue by shoults14** [goldshellminer/firmware#73]
Hello, 

I have 4 KD6s and 3 of them are the 2 board version (29Th) running on 2.50.SA and the other one is 4 boards on 2.40.SA (has been a PITA and is only 26Th). The 3 mine perfectly where the 1 was giving me a 75% rejection rate along with other intermittent issues (board 3 cutting out). I saw an issue already posted on here that says you need to update to 2.1.1 to fix the 75% rejection rate but Goldshell closed the issue with not even commenting with the updated firmware to fix. This firmware fix is not listed in Goldshell's archives or anywhere, so to fix, I tried to update to the latest 2.2.10 on their website and now it does not hash at all and it only shows 2 boards on the dashboard so clearly this is for the newer 2.50 hardware (29Th). Frustrating for sure and really wish I just had 4 of the better and more reliable 29Th versions. 

@goldshellminer please help ASAP!

**Comment by goldshellminer** [comment]
Dear customer, pls contact the support team for more help directly, open an online ticket via the website: https://goldshellhelp.zendesk.com/hc/en-us/requests/new?ticket_form_id=8017416782745
