### ISSUE TITLE
MiniDoge: IP won't update, find my goldshell

### ISSUE THREAD

**Issue by Dashinglight1945** [goldshellminer/firmware#74]
My mini doge won't allow me access to the dashboard. Findmygoldshell.com keeps showing the old IP. I found a workaround to get into the dashboard by logging into the miner via WiFi. But there are no new updates to install. I'm on 2.2.1. Don't know what to do?

**Comment by goldshellminer** [comment]
This solution may help you, flash your micro SD card and see if it fix. If still not working, pls contact the after-sale team to get more solutions.
