### ISSUE TITLE
KD-Box Pro unable to connect to hidden SSID Wi-Fi and also unable to disable Wi-Fi on firmware 2.2.4

### ISSUE THREAD

**Issue by PurebredTed** [goldshellminer/firmware#77]
KD-Box Pro 2.2.4
I have 2 brand new KD-Box Pros on firmware 2.2.4
I can't turn off Wi-Fi and they are broadcasting an SSID which is unexpected for a client.  I saw a suggestion to first connect to a Wi-Fi network and then you'll be able to disable it.  I tried that, but I can't connect to a hidden SSID Wi-Fi.
I haven't started to debug or look at logs yet.

I also just had to power cycle last night after its first week of mining.  All other older models are fine, just the new Pros have an issue.  One of the KD-Box Pros dropped off and stopped mining.  The other had sporadic hashrates.

KD-Box Pro Config:
Using ethernet | 2 Pools configured and using IP instead of URL and only difference is IP address | All Static IP setup | Cloud Control disabled | 2 KD-Box Pros hooked up to EVGA 1600 PSU (plenty of power)

**Comment by goldshellminer** [comment]
Pls contact the support team via website ticket, they will help and guide you to disable the WIFI. Llink: https://goldshellhelp.zendesk.com/hc/en-us/requests/new?ticket_form_id=8017416782745
