### ISSUE TITLE
LB-Lite 2.2.3 and LB-Box 2.2.3

### ISSUE THREAD

**Issue by kwaichangdave** [goldshellminer/firmware#79]
LB-Lite 2.2.3 and LB-Box 2.2.3 will not connect to Nicehash stratum (stratum+tcp://lbry.auto.nicehash.com:9200)
Here is what Nicehash support says: 
"Unfortunately that ASIC is not supported on our platform. Other users have confirmed that they cannot hold a connection to our servers and get disconnected. We are using the standard stratum protocol so please contact the manufacturer regarding this compatibility issue.

Kind regards,
NiceHash Team"

**Comment by goldshellminer** [comment]
The R&D team has received your request and worked on this. You can try connecting to Dxpool and ViaBTC as other options.
