### ISSUE TITLE
Afer the new firmware update CK-5 miner isn't mining and both red and green light are always on

### ISSUE THREAD

**Issue by Anubix8** [goldshellminer/firmware#8]

**Comment by GGamer162008** [comment]
Can someone tell me what is wrong.
![IMG-e7c11e6a4aef3ba2e2545fec6981dc81-V](https://user-images.githubusercontent.com/71311961/125049265-16189b80-e0a1-11eb-938d-68987bef13fe.jpg)

**Comment by Jwiscovitch** [comment]
I just downloaded the newest firmware and am having the same issue. I also tried to put the SD card in with the 2.0.3 firmware and nothing happened. I will sometimes get the red and green lights flashing in sync with each other. Still....not able to connect to the unit or anything. Has anyone found a fix?

**Comment by MelasDigital** [comment]
I have the same problem with CK5. After the update, both LEDs are lit, the IP gets, but the web interface is unavailable.

**Comment by Jwiscovitch** [comment]
I had to sd flash reset it. I did re-downloaded the new firmware and it works great now!

**Comment by raminxxx** [comment]
> I had to sd flash reset it. I did re-downloaded the new firmware and it works great now!
how do you flash via sd card please explain i have this problem but don't know how to do that!

**Comment by THECOMPANY2** [comment]
do somone hav the flash fill ASAP

**Comment by zhaohaominer** [comment]
If you need to add my QQ notes GitHub, I can help

If you need to add my discord notes GitHub, I can help

I can provide burning files

QQ:86874708 Discord:zhaohao#5572

**Comment by hakanhande** [comment]
Hey i need to this flash image i have same problem can you share with me 
my email   busarider@outlook.com 

zhaohaominer if you hear me can you share discord link again cuz its not working right now

**Comment by M4773090** [comment]
Someone have IMG file to flash miner by SD?
