### ISSUE TITLE
Goldshell Box Miner Clears out my pools and adds default pools

### ISSUE THREAD

**Issue by TypicDuckling5** [goldshellminer/firmware#80]
I have three doge miners along with one KD Box pro. Its very inconsistent but the miners will be connected to the pool as normal and then will randomly swap pools even with them locked in the settings. I've tried a lot of options and nothing seems to work. All 4 of the miners will swap pools at the same time, so I'm not sure if its a network issue or hardware issue.

**Comment by goldshellminer** [comment]
Flash sd card and firmware would fix the issue. Pls contact the support team via online ticket, they will guide you on how to flash it: https://www.goldshell.com/support-center/
