### ISSUE TITLE
Dear goldshell

### ISSUE THREAD

**Issue by chris-the-miner** [goldshellminer/firmware#85]
Hi goldshell
Can you guys change the software so we can select power mode for the first CK box, low power mode/hashrate power mode.
This can be very useful for us with a high electric rate or if we want to run our miners more efficiently. CK-Box II have this.. so can you implement it? Thank you!

**Comment by goldshellminer** [comment]
Hey, thanks for your feedback. The R&D team will take into consideration your suggestion, and work on it.

**Comment by Professorfordy** [comment]
Dear goldshellminer i tried to dowdload vresion 2.2.6 for the goldshell mini doge 2 but sadly it wouldn't copy flash over to my miner
