### ISSUE TITLE
Mini Doge 2.2.5 firmware on Nicehash

### ISSUE THREAD

**Issue by kwaichangdave** [goldshellminer/firmware#86]
The 2.2.4 and 2.2.5 firmware for mini doge miner supports nicehash but it does not support xnsub. In order to efficiently mine with the scrypt algo on Nicehash the miner needs to use xnsub (extranonce). Without xnsub, the mini doge miner is inefficient on nicehash and is not worth it to use on Nicehash. Please add xnsub support.

**Comment by goldshellminer** [comment]
Thanks for you reporting it, our R&D team will have a deep discussion with Nicehash, and trying to upgrade.
