### ISSUE TITLE
KD - MAX Sleep Mode

### ISSUE THREAD

**Issue by jpmi1** [goldshellminer/firmware#87]
I see a dropdown for the powerplan in the latest firmware for the KD- MAX.

When will you implement the ability to kill the mining process and reduce fan speed? This is crucial for any operation doing demand response.

**Comment by goldshellminer** [comment]
You could find powerplan function in the Hub platform, which applies to default and low-power mode miners, eg: LITE series, BOX II series. 
Currently, KDMAX only supports default hash mode, can't be available for powerplan setting.
