### ISSUE TITLE
SC BOX REJECT RATE

### ISSUE THREAD

**Issue by kwaichangdave** [goldshellminer/firmware#88]
SCBOX with firmware 2.2.4 is getting 40% or more rejected shares on SCP DXPool. It gets 0.3% rejects on SCPrimePool. DXPool says this is a goldshell problem and requires a firmware update. I'm not sure this is right. Can you please investigate.

**Comment by goldshellminer** [comment]
Hi, Goldshell customer

We are now working on the new firmware for SCBOX to fix this pool rejection problem and should be released soon. 
If you have another technical issue, please go to [](https://goldshellhelp.zendesk.com/hc/en-us/requests/new?ticket_form_id=8017416782745) for further assistance.

Please be patient during this time. Thank you for your understanding and wish you can enjoy your day.
