### ISSUE TITLE
wifi enable/disable

### ISSUE THREAD

**Issue by isoneguy** [goldshellminer/firmware#89]
can you resolve the wifi issue so that we dont have to manually remove the wifi antennas with a hammer or something.

need to be able to disable both the wifi hotspot and the wifi network connection without fancy ssh work.

thanks,

**Comment by goldshellminer** [comment]
Hi, thanks for your suggestion, will take it into serious consideration.

**Comment by isoneguy** [comment]
wasnt resolved.
